version: '3.8'

services:
  easy-post-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:3000']
      interval: 30s
      timeout: 10s
      retries: 3
