version: '3.8'

services:
  react-vite:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
